name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          check-latest: true
      - uses: pnpm/action-setup@v2
      - run: pnpm install
      - run: pnpm run format-check
      - run: pnpm run lint
